const foodList = [
  {
    src: require("./img/비어치킨.jpg"),
    id: 1,
    hash: ["#비어", "#치킨"],
    name: "비어치킨",
    view: 300,
  },
  {
    src: require("./img/진라거치아바타.jpg"),
    id: 2,
    hash: ["#치아바타"],
    name: "진라거치아바타",
    view: 310,
  },
  {
    src: require("./img/비어브레드.jpg"),
    id: 3,
    hash: ["#브레드"],
    name: "비어브레드",
    view: 320,
  },
  {
    src: require("./img/전자레인지브라우니.jpg"),
    id: 4,
    hash: ["#핫케이크믹스", "#핫쵸코", "#브라우니"],
    name: "전자레인지브라우니",
    view: 313,
  },
  {
    src: require("./img/유자고구마샐러드.jpg"),
    id: 5,
    hash: [],
    name: "유자고구마샐러드",
    view: 280,
  },
  {
    src: require("./img/팥스타.jpg"),
    id: 6,
    hash: ["#팥칼국수", "#동지", "#겨울간식"],
    name: "팥스타",
    view: 500,
  },
  {
    src: require("./img/오이무침.jpg"),
    id: 7,
    hash: ["#반찬", "#오이무침", "#다시마식초"],
    name: "오이무침",
    view: 452,
  },
  {
    src: require("./img/연어장.jpg"),
    id: 8,
    hash: ["#간편장아찌", "#연어", "#간편요리"],
    name: "연어장",
    view: 380,
  },
  {
    src: require("./img/케일장아찌.jpg"),
    id: 9,
    hash: ["#장아찌", "#케일장아찌", "#간편장아찌소스"],
    name: "케일장아찌",
    view: 345,
  },
  {
    src: require("./img/두부참치마요샌드위치.jpg"),
    id: 10,
    hash: ["#참치", "#샌드위치", "#1/2하프마요네스"],
    name: "두부참치마요샌드위치",
    view: 412,
  },
  {
    src: require("./img/오트밀토마토리조또.jpg"),
    id: 11,
    hash: ["#다이어트", "#닭가슴살", "#브런치"],
    name: "오트밀토마토리조또",
    view: 454,
  },
  {
    src: require("./img/단호박시나몬그라탕.jpg"),
    id: 12,
    hash: ["#단호박", "#그라탕", "#1/2하프마요네스"],
    name: "단호박시나몬그라탕",
    view: 400,
  },
  {
    src: require("./img/순후추떡국라면.jpg"),
    id: 13,
    hash: ["#떡국", "#옛날쌀떡국", "#설날"],
    name: "순후추떡국라면",
    view: 312,
  },
  {
    src: require("./img/어묵 진짬뽕.jpg"),
    id: 14,
    hash: ["#진짬뽕", "#어묵", "#꿀조합"],
    name: "어묵 진짬뽕",
    view: 312,
  },
  {
    src: require("./img/야끼소바빵.jpg"),
    id: 15,
    hash: ["#철판뽀끼", "#야끼소바", "#일본요리"],
    name: "야끼소바빵",
    view: 312,
  },
];

export default foodList;
